# Generated by Django 4.1.4 on 2023-01-23 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dwitter", "0002_dwitts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dwitts",
            name="body",
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name="dwitts",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="dwitts",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="dweets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
